kind: pipeline
type: kubernetes
name: build-npm

steps:
  - name: build
    image: node
    commands:
      - npm install
      - mkdir dist
      - tar czf /tmp/backend.tar.gz -X tar-exclude.txt $(pwd)
  - name: publish github
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_api_key
      files: /tmp/backend.tar.gz
      checksum:
        - md5
        - sha256
    when:
      event:
      - tag
    depends_on:
    - build
  - name: publish-docker
    image: plugins/docker
    settings:
      repo: akhfa/pikobar-pelaporan-backend
      auto_tag: true
      username: akhfa
      password:
        from_secret: dockerhub_password
      dockerfile: Dockerfile.release
      purge: true
    depends_on:
    - build
trigger:
  branch:
    - master
  event:
    - pull_request
    - push
    - tag
