kind: pipeline
type: kubernetes
name: build-npm

steps:
  - name: build
    image: node
    commands:
      - npm install
      - mkdir dist
      - tar czvf dist/backend.tar.gz -X tar-exclude.txt $(pwd)
  - name: publish
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_api_key
      files: dist/backend.tar.gz
      checksum:
        - md5
        - sha256
    when:
      event:
      - tag
trigger:
  branch:
    - master
  event:
    - pull_request
    - push
    - tag
