kind: pipeline
type: kubernetes
name: build-npm

steps:
  - name: build
    image: node
    commands:
      - npm install
      - tar czvf backend.tar.gz -X tar-exclude.txt $(pwd)
  - name: publish
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_api_key
      files: backend.tar.gz
    when:
      event:
      - tag
trigger:
  branch:
    - master
  event:
    - pull_request
    - push
    - tag
